//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advertisement
    {
        public int AdID { get; set; }
        public int UserID { get; set; }
        public Nullable<System.DateTime> PublicationDate { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public string Photo { get; set; }
    
        public virtual AdCategory AdCategory { get; set; }
        public virtual AdType AdType { get; set; }
        public virtual City City { get; set; }
        public virtual StatusType StatusType { get; set; }
        public virtual Users Users { get; set; }
    }
}
