//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advertisement
    {
        public int AdID { get; set; }
        public int UserID { get; set; }
        public System.DateTime PublicationDate { get; set; }
        public int CategoryID { get; set; }
        public int CityID { get; set; }
        public int TypeID { get; set; }
        public int StatusID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
    
        public virtual AdCategory AdCategory { get; set; }
        public virtual AdType AdType { get; set; }
        public virtual City City { get; set; }
        public virtual StatusType StatusType { get; set; }
        public virtual Users Users { get; set; }
    }
}
